= Software Factory Foundations with OpenShift Dev Spaces
:navtitle: Home

== Introduction

Welcome to this quick course on the _**Software Factory Foundations with OpenShift Dev Spaces**_.
This course is the `second` in a series of `six` courses about **Application Platform Delivery**:

* https://redhatquickcourses.github.io/etx-app-delivery-module1/etx-app-delivery-module1/1/index.html[_Introduction to Application Platforms and Platform Engineering_, window=browser]
* https://redhatquickcourses.github.io/etx-app-delivery-module2/etx-app-delivery-module2/1/index.html[_Software Factory Foundations with OpenShift Dev Spaces_, window=browser] (_This course_)
* https://redhatquickcourses.github.io/etx-app-delivery-module3/etx-app-delivery-module3/1/index.html[_Software Delivery with OpenShift Pipelines and GitOps_, window=browser]
* https://redhatquickcourses.github.io/etx-app-delivery-module4/etx-app-delivery-module4/1/index.html[_DevEx with Red Hat Developer Hub_, window=browser]
* https://redhatquickcourses.github.io/etx-app-delivery-module5/etx-app-delivery-module5/1/index.html[_Application Modernization with MTA_]
* https://redhatquickcourses.github.io/etx-app-delivery-module6/etx-app-delivery-module6/1/index.html[_Trusted Software Supply Chain (TSSC)_, window=browser]

== What's in this course?

In this module, you'll learn how an Application Platform enables a **Software Factory** and why **Git** is fundamental to modern application delivery. You'll prepare the required platform services, configure a cloud-native development environment using **Red Hat OpenShift Dev Spaces** and **GitLab**, and deploy the **ETX App Base application**.

By the end of this module, you'll have a fully configured development environment and a running application that you'll use throughout the remainder of this learning path.

Duration: 3:00 hours

== Contributors

The PTL team acknowledges the valuable contributions of the following Red Hat associates:

* Andrew Block (SME)
* Bill Wheatley (SME)
* Bryan Saunders (SME)
* Evan Shortiss (SME)
* Julio Villarreal Pelegrino (SME)
* Kristopher Godek (SME)
* Roman Martin Gil (SME)
* Senthil Kumar (SME)
* Sergio Canales Espinoza (SME)
* Yogita Soni (Content Architect)
* Lisa Edgell (Learning Product Manager)
* Caitlyn Rymarchyk (Learning Product Manager)
* Anna Swicegood (Learning Product Manager)

== Objectives

On completing this course, you should be able to:

* Explain how an Application Platform enables a **Software Factory** for standardized software delivery.
* Describe the role of Git in collaborative development, CI/CD pipelines, and GitOps workflows.
* Configure **Red Hat OpenShift Dev Spaces** and integrate it with **GitLab**.
* Create and use a reusable Devfile to provision cloud-native development workspaces.
* Launch a browser-based development environment and connect it to the application platform.
* Deploy the **ETX App Base application** and verify that it is running successfully.

== Prerequisites

This course assumes that you have the following prior experience:

1. https://training-lms.redhat.com/lmt/clmscoursedetails.prmain?in_sessionId=5034892A2J492834&in_selfContained=N&in_offeringId=57857955&in_tab_group=&in_from_module=CLMSBROWSEV2.PRMAIN[Red Hat OpenShift Container Platform (OCP) Technical Overview] or Kubernetes Basics