:imagesdir: ../images

= Dev Spaces Overview
:navtitle: Dev Spaces Overview

== Cloud Development Environments (CDEs): What and Why?

With the increasing capabilities provided by the cloud and modern Javascript front-end user
interfaces to host applications of all types, it makes sense to explore the concept of a portable,
cloud-based developer environment that can be accessed by a diverse group of developers spread over
multiple geographies, with just a modern browser.

Enter the concept of a **Cloud Development Environment**.

According to https://www.gartner.com/reviews/market/cloud-development-environments-cdes[Gartner^]:

"Cloud development environments (CDEs) provide software developers with remote, ready-to-use access
to a cloud-hosted development environment with minimal effort for setup and configuration. They
comprise elements of a traditional IDE, such as code editing, debugging, code review, and code
collaboration. They also provide consistent, secure developer access to preconfigured development
workspaces. This frees them from setting up their own local environments, eliminating the need to
install and maintain dependencies, software development kits, security patches, and plug-ins. Their
seamless integration with Git-based repositories and continuous integration/continuous delivery
(CI/CD) tools enhances developer productivity and developer experience. CDEs provide a scalable way
to support a distributed workforce and hybrid work environments."
-- Gartner, "What are Cloud Development Environments (CDEs)?"

The advantages of a CDE are as follows:

* Near-instant provisioning of developer environments, on-demand for a new developer
* Ability to reproduce cloud-native production environments in development (to speedy releases, and reduce the cliché of _“but, it works on my machine!...”_)
* Bring the day-to-day tasks that a developer does on his local machine (writing code, testing, debugging, and more), to a web-based IDE to improve the same developer experience.
* Seamless switching between different projects with different stacks and different versions of programming language runtimes
* Centralized security and access to source code backed by enterprise security standards (OAuth/OIDC, TLS)
* Fine-grained resource control and multi-tenancy.
